name: anaconda-publish

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Set up conda
        run: |
            conda install -y anaconda-client conda-build
            conda config --set anaconda_upload no
      - name: Build and publish to conda
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        run: |
            conda build conda -c conda-forge --config-file conda/conda_build_config.yaml
            conda convert fusion-energy/brep_to_h5m/0.2.1/linux-64/*.tar.bz2 --platform osx-64
            anaconda upload -f fusion-energy/brep_to_h5m/0.2.1/linux-64/*.tar.bz2
