
# This CI will launch a Docker image that contains all the dependencies required
# within that image the pytest test suite is run 


name: CI with install

on:
  pull_request:    
    branches:
    - develop
    - main
 
jobs:
  testing:
    runs-on: ubuntu-latest
    container:
      image: continuumio/miniconda3
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: install dependencies package
        run: |
          apt update -y
          apt-get install ffmpeg libsm6 libxext6  -y
          conda install -c conda-forge gmsh
          conda install -c conda-forge python-gmsh
          conda install -c conda-forge moab


      - name: install package
        run: |
          pip install .
          python -c "import brep_to_h5m"

      - name: install package with tests
        run: |
          pip install .[tests]

      - name: Run test_utils
        run: |
          pytest tests -v 
